"""Migration for user profile friend code."""

# Generated by Django 5.2 on 2025-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_userprofile_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friend_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
