# Generated by Django 5.2.1 on 2025-06-19 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_userprofile_friend_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={
                "ordering": ("set", "number"),
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="friendrequest",
            options={
                "verbose_name": "Friend Request",
                "verbose_name_plural": "Friend Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="pack",
            options={
                "ordering": ("set", "name"),
                "verbose_name": "Pack",
                "verbose_name_plural": "Packs",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonset",
            options={
                "ordering": ("release_date",),
                "verbose_name": "Pokémon Set",
                "verbose_name_plural": "Pokémon Sets",
            },
        ),
        migrations.AlterModelOptions(
            name="rarity",
            options={
                "ordering": ("order",),
                "verbose_name": "Rarity",
                "verbose_name_plural": "Rarities",
            },
        ),
        migrations.AlterModelOptions(
            name="rarityprobability",
            options={
                "verbose_name": "Rarity Probability",
                "verbose_name_plural": "Rarity Probabilities",
            },
        ),
        migrations.AlterModelOptions(
            name="usercard",
            options={"verbose_name": "User Card", "verbose_name_plural": "User Cards"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="version",
            options={"verbose_name": "Version", "verbose_name_plural": "Versions"},
        ),
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Card Name"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="number",
            field=models.CharField(
                db_index=True, max_length=10, verbose_name="Card Number"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="tracker.rarity",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Accepted"),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="pack",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Pack Name"
            ),
        ),
        migrations.AlterField(
            model_name="pack",
            name="rarity_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packs",
                to="tracker.version",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonset",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the set",
                max_length=100,
                verbose_name="Set Name",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonset",
            name="number",
            field=models.CharField(
                db_index=True,
                help_text="Set code or number",
                max_length=10,
                verbose_name="Set Number",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonset",
            name="release_date",
            field=models.DateField(
                db_index=True,
                help_text="Release date of the set",
                verbose_name="Release Date",
            ),
        ),
        migrations.AlterField(
            model_name="rarity",
            name="display_name",
            field=models.CharField(
                help_text="Display name for rarity",
                max_length=4,
                unique=True,
                verbose_name="Display Name",
            ),
        ),
        migrations.AlterField(
            model_name="rarity",
            name="image_name",
            field=models.CharField(
                blank=True,
                help_text="Optional image filename for rarity symbol",
                max_length=100,
                null=True,
                verbose_name="Image Name",
            ),
        ),
        migrations.AlterField(
            model_name="rarity",
            name="name",
            field=models.CharField(
                help_text="Internal rarity name",
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="Rarity Name",
            ),
        ),
        migrations.AlterField(
            model_name="rarity",
            name="order",
            field=models.PositiveSmallIntegerField(
                help_text="Display order for rarity", unique=True, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="rarity",
            name="repeat_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many times the rarity symbol repeats",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Repeat Count",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_fifth",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Fifth Slot Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_first",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="First Slot Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_fourth",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Fourth Slot Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="rarity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="probabilities",
                to="tracker.rarity",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rarity_probabilities",
                to="tracker.version",
            ),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_cards",
                to="tracker.card",
            ),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="friend_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Friend Code"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="public",
            field=models.BooleanField(default=True, verbose_name="Public Profile"),
        ),
        migrations.AlterField(
            model_name="version",
            name="display_name",
            field=models.CharField(
                help_text="Display name for the version",
                max_length=10,
                unique=True,
                verbose_name="Display Name",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="name",
            field=models.CharField(
                help_text="Short code for the version, e.g. V1",
                max_length=3,
                primary_key=True,
                serialize=False,
                verbose_name="Short Name",
            ),
        ),
        migrations.CreateModel(
            name="CardNameTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(db_index=True, max_length=10)),
                ("localized_name", models.CharField(db_index=True, max_length=100)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="tracker.card",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Name Translation",
                "verbose_name_plural": "Card Name Translations",
                "indexes": [
                    models.Index(
                        fields=["language_code", "localized_name"],
                        name="tracker_car_languag_d27461_idx",
                    )
                ],
                "unique_together": {("card", "language_code")},
            },
        ),
    ]
