# Generated by Django 5.2.1 on 2025-06-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_card_options_alter_friendrequest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackNameTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(db_index=True, max_length=10)),
                ("localized_name", models.CharField(db_index=True, max_length=100)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="tracker.pack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack Name Translation",
                "verbose_name_plural": "Pack Name Translations",
                "indexes": [
                    models.Index(
                        fields=["language_code", "localized_name"],
                        name="tracker_pac_languag_4f7081_idx",
                    )
                ],
                "unique_together": {("pack", "language_code")},
            },
        ),
        migrations.CreateModel(
            name="PokemonSetNameTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(db_index=True, max_length=10)),
                ("localized_name", models.CharField(db_index=True, max_length=100)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="tracker.pokemonset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Set Name Translation",
                "verbose_name_plural": "Set Name Translations",
                "indexes": [
                    models.Index(
                        fields=["language_code", "localized_name"],
                        name="tracker_pok_languag_d85529_idx",
                    )
                ],
                "unique_together": {("set", "language_code")},
            },
        ),
    ]
