# Generated by Django 5.2.1 on 2026-01-03 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_version_to_generation(apps, schema_editor):  # noqa: ARG001
    """Migrate data from Version model to Generation model."""
    Version = apps.get_model("tracker", "Version")
    Generation = apps.get_model("tracker", "Generation")

    for version in Version.objects.all():
        # Create corresponding Generation record
        Generation.objects.create(
            name=version.name,
            display_name=getattr(version, "display_name", version.name),
            description=getattr(version, "description", ""),
        )


def reverse_migrate_generation_to_version(apps, schema_editor):  # noqa: ARG001
    """Reverse migration - recreate Version records from Generation."""
    Version = apps.get_model("tracker", "Version")
    Generation = apps.get_model("tracker", "Generation")

    for generation in Generation.objects.all():
        Version.objects.create(
            name=generation.name,
            display_name=generation.display_name,
            description=generation.description,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_pokemonset_available_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Short code for the generation, e.g. G1",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name for the generation",
                        max_length=10,
                        unique=True,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this generation",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generation",
                "verbose_name_plural": "Generations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PackType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal pack type name, e.g. normal, shiny, god",
                        max_length=20,
                        verbose_name="Pack Type Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name for the pack type",
                        max_length=30,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "slot_count",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="How many card slots this pack type contains",
                        verbose_name="Number of Slots",
                    ),
                ),
                (
                    "occurrence_probability",
                    models.FloatField(
                        help_text="Probability of getting this pack type (as decimal, e.g. 0.05238 for 5.238%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Occurrence Probability",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this pack type",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack Type",
                "verbose_name_plural": "Pack Types",
                "ordering": ("generation", "-occurrence_probability"),
            },
        ),
        # Migrate data from Version to Generation before changing foreign keys
        migrations.RunPython(
            migrate_version_to_generation,
            reverse_migrate_generation_to_version,
        ),
        migrations.RemoveIndex(
            model_name="rarityprobability",
            name="tracker_rar_version_36661b_idx",
        ),
        migrations.AddField(
            model_name="rarityprobability",
            name="probability_slot6",
            field=models.FloatField(
                default=0.0,
                help_text="For special pack types like shiny packs with extra cards",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Slot 6 Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_slot1",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Slot 1 Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_slot2",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Slot 2 Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_slot3",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Slot 3 Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_slot4",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Slot 4 Probability",
            ),
        ),
        migrations.AlterField(
            model_name="rarityprobability",
            name="probability_slot5",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Slot 5 Probability",
            ),
        ),
        migrations.AddField(
            model_name="pokemonset",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                help_text="The generation this set belongs to (defines pack types and rarity probabilities)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pokemon_sets",
                to="tracker.generation",
                verbose_name="Generation",
            ),
        ),
        migrations.AddField(
            model_name="rarityprobability",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rarity_probabilities",
                to="tracker.generation",
            ),
        ),
        migrations.AlterField(
            model_name="pack",
            name="rarity_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packs",
                to="tracker.generation",
            ),
        ),
        migrations.AddIndex(
            model_name="pokemonset",
            index=models.Index(
                fields=["generation"], name="tracker_pok_generat_74f12c_idx"
            ),
        ),
        migrations.AddField(
            model_name="packtype",
            name="generation",
            field=models.ForeignKey(
                help_text="The generation this pack type belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pack_types",
                to="tracker.generation",
                verbose_name="Generation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rarityprobability",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="rarityprobability",
            name="pack_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The pack type this probability applies to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rarity_probabilities",
                to="tracker.packtype",
                verbose_name="Pack Type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rarityprobability",
            unique_together={("generation", "pack_type", "rarity")},
        ),
        migrations.AddIndex(
            model_name="rarityprobability",
            index=models.Index(
                fields=["generation", "pack_type", "rarity"],
                name="tracker_rar_generat_139334_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packtype",
            unique_together={("generation", "name")},
        ),
        migrations.RemoveField(
            model_name="rarityprobability",
            name="version",
        ),
        migrations.DeleteModel(
            name="Version",
        ),
    ]
