# Generated by Django 5.2.1 on 2026-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_generation_packtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generation",
            name="display_name",
            field=models.CharField(
                help_text="Display name for the generation",
                max_length=20,
                unique=True,
                verbose_name="Display Name",
            ),
        ),
    ]
