# Generated by Django 5.2.1 on 2026-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_alter_generation_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="friend_code",
            field=models.CharField(
                blank=True,
                help_text="Up to 10 characters.",
                max_length=10,
                null=True,
                verbose_name="Friend Code",
            ),
        ),
    ]
