# Generated by Django 5.2.18 on 2026-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_alter_userprofile_friend_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rarityprobability",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="card",
            name="is_foil",
            field=models.BooleanField(
                default=False,
                help_text="Parallel-foil print of a card that also exists as a standard print (deluxe packs draw the two from different slots)",
                verbose_name="Foil",
            ),
        ),
        migrations.AddField(
            model_name="rarityprobability",
            name="is_foil",
            field=models.BooleanField(
                default=False,
                help_text="Applies to the parallel-foil prints of this rarity (deluxe packs)",
                verbose_name="Foil",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rarityprobability",
            unique_together={("generation", "pack_type", "rarity", "is_foil")},
        ),
    ]
