# Generated by Django 5.2 on 2025-05-02 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('release_date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['release_date'],
                'indexes': [models.Index(fields=['release_date'], name='tracker_pok_release_a22568_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='tracker.pokemonset')),
                ('rarity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.version')),
            ],
            options={
                'ordering': ['set', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=4, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rarities',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='tracker_rar_order_5aac50_idx')],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('packs', models.ManyToManyField(blank=True, related_name='cards', to='tracker.pack')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tracker.pokemonset')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.rarity')),
            ],
            options={
                'ordering': ['set', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RarityProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_first', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probability_fourth', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probability_fifth', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.rarity')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.version')),
            ],
            options={
                'verbose_name_plural': 'Rarity Probabilities',
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['set', 'number'], name='tracker_car_set_id_a214d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('set', 'number')},
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['user', 'card'], name='tracker_use_user_id_017148_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together={('user', 'card')},
        ),
        migrations.AddIndex(
            model_name='rarityprobability',
            index=models.Index(fields=['version', 'rarity'], name='tracker_rar_version_36661b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rarityprobability',
            unique_together={('version', 'rarity')},
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['set', 'name'], name='tracker_pac_set_id_86e2bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together={('set', 'name')},
        ),
    ]
